inherit: true

build:
  nodes:
    analysis:
      environment:
        php:
          pecl_extensions:
            - ast
      dependencies:
        override:
          - composer install --prefer-dist
      tests:
        override: [php-scrutinizer-run]

tools:
    external_code_coverage: true

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: [src/*, tests/*]
