inherit: true

build:
  nodes:
    analysis:
      dependencies:
        before:
          - sudo apt-get install -y php-ast
      tests:
        override: [php-scrutinizer-run]

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: [src/*, tests/*]
