inherit: true

build:
  nodes:
    analysis:
      environment:
        variables:
          SS_ENVIRONMENT_TYPE: dev
          SS_DATABASE_CLASS: SQLite3Database
          SS_DATABASE_NAME: xxx
          SS_DATABASE_USERNAME: xxx
          SS_DATABASE_PASSWORD: xxx
          SS_DEFAULT_ADMIN_USERNAME: admin
          SS_DEFAULT_ADMIN_PASSWORD: admin
        php:
          version: "7.4"
          pecl_extensions:
            - ast
      dependencies:
        override:
          - composer validate
          - composer install --no-interaction --verbose --profile --prefer-dist
      tests:
        override: [php-scrutinizer-run]

tools:
    external_code_coverage: true

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: [src/*, tests/*]
