inherit: true

build:
  dependencies:
    override:
      - composer install --prefer-dist
  nodes:
    analysis:
      environment:
        php:
          pecl_extensions:
            - ast
      tests:
        override: [php-scrutinizer-run]

tools:
    external_code_coverage: true

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: [src/*, tests/*]
