language: php

env:
  - SS_ENVIRONMENT_TYPE=dev
  - SS_DATABASE_CLASS=SQLite3Database
  - SS_DATABASE_NAME=xxx
  - SS_DATABASE_USERNAME=xxx
  - SS_DATABASE_PASSWORD=xxx
  - SS_DEFAULT_ADMIN_USERNAME=admin
  - SS_DEFAULT_ADMIN_PASSWORD=admin

matrix:
  include:
    - php: 7.4
      env:
        - RECIPE_VERSION=4.10.x-dev
        - PHPUNIT_COVERAGE_TEST=1
        - PHPUNIT_TEST_ALL=1
    - php: 8.0
      env:
        - RECIPE_VERSION=4.10.x-dev
        - PHPUNIT_TEST_ALL=1

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - pecl install ast
  - pecl install pcov

  - composer self-update 2.2.12
  - composer validate
  - composer require --no-update silverstripe/framework:"$RECIPE_VERSION"
  - composer install --no-interaction --verbose --profile

script:
  - if [[ $PHPUNIT_TEST_ALL ]]; then composer test:all; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then composer test:coverage:ci; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f ./build/coverage/coverage-xml/index.xml -F php; fi
