name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  SCRUTINIZER_TOKEN: ${{ secrets.SCRUTINIZER_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  php_extensions: ctype, dom, fileinfo, hash, intl, mbstring, session, simplexml, tokenizer, xml, gd, sqlite3, pcov, opcache, tidy, zip
  SS_DATABASE_CLASS: SQLite3Database
  SS_DATABASE_SERVER: localhost
  SS_DATABASE_NAME: silverstripe
  SS_DATABASE_USERNAME: root
  SS_DATABASE_PASSWORD: silverstripe
  SS_DEFAULT_ADMIN_USERNAME: admin
  SS_DEFAULT_ADMIN_PASSWORD: admin
jobs:
  test:
    timeout-minutes: 15
    name: Testing with SilverStripe ${{ matrix.versions.silverstripe }} & PHP ${{ matrix.versions.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - php: '7.3'
            silverstripe: '4.10.x-dev'
          - php: '7.4'
            silverstripe: '4.10.x-dev'
          - php: '8.0'
            silverstripe: '4.10.x-dev'
          - php: '8.1'
            silverstripe: '4.10.x-dev'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.versions.php }}
          extensions: ${{ env.php_extensions }}
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer
        run: composer validate

      - name: Install SilverStripe
        run: composer require --no-update silverstripe/recipe-core:${{ matrix.versions.silverstripe }}

      - name: Install Requirements
        run: composer install --no-interaction --no-progress --optimize-autoloader --verbose --profile

      - name: Run Migration
        run: ./vendor/bin/sake dev/build "flush=all"

      - name: Run phpcs
        run: vendor/bin/phpcs -p .

      - name: Run phpstan
        run: vendor/bin/phpstan analyse -l 9 src tests

      - name: Run phpunit
        run: vendor/bin/phpunit
  coverage:
    timeout-minutes: 15
    name: Code Coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - php: '8.1'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.versions.php }}
          extensions: ${{ env.php_extensions }}
          coverage: xdebug2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer
        run: composer validate

      - name: Install Requirements
        run: composer install --no-interaction --no-progress --optimize-autoloader --verbose --profile

      - name: Run Migration
        run: ./vendor/bin/sake dev/build "flush=all"

      - name: Run phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload codecov coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml

      - name: Upload Scrutinizer coverage
        uses: sudo-bot/action-scrutinizer@latest
        with:
            cli-args:  --access-token=${{ env.SCRUTINIZER_TOKEN }} --format=php-clover ./coverage.xml
